apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-lb-binding-nginx-ingress-lb-basic-infra-dsv
  namespace: ingress-nginx
  labels:
    gitups.io/binding: lb-ip-pool
data:
  serviceName: ingress-nginx-controller
  poolName: ingress-pool
  cidrs: |
    - 172.18.255.200-172.18.255.210
