apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-env-config
  namespace: vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: support-services
data:
  profile: "dsv"
  service-url: "http://vault.vault.svc.cluster.local:8200"

