apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-user-argocd-gitea-bot-support-services-dev-values
  namespace: gitea
  labels:
    app.kubernetes.io/managed-by: gitups
    app.kubernetes.io/component: script-provisioner
    app.kubernetes.io/instance: gitea-user-argocd-gitea-bot-support-services-dev
data:
  values.json: |
    {
      "namespace": "gitea",
      "token": "e2e-argocd-bot-token",
      "url": "http://gitea.gitea.svc.cluster.local:3000/",
      "username": "argocd-bot"
    }
