apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  gitups.io/apply-wave: "2"
  gitups.io/readiness: '[{"kind":"Deployment","name":"argocd-server","namespace":"argocd","condition":"Available"}]'
kind: Kustomization
resources:
- repo-secret.yaml
