apiVersion: gitups/v1alpha1
kind: FullProvision
metadata:
  name: nginx-metallb-binding
spec:
  packages:
  - applyWave: 0
    domain: install
    installMethod: raw
    instance: olm
    packageInstance: olm
    renderedPaths:
      dir: packages/olm/install/raw
      repo: basic-infra
    renderer: raw
    repository: basic-infra
    resolvedValues:
      catalog:
        image:
          digest: 9fbfd70da2cedae8754fb8ed1b4d9c55733b5a7e06685d34aa415063cd964743
          repository: quay.io/operatorhubio/catalog
      images:
        configmapOperatorRegistry:
          digest: 3e259e1e339ad9d388cb611745312ae1c0390c9338bfd6d9965811e1978d9d1c
          repository: quay.io/operator-framework/configmap-operator-registry
        olm:
          digest: 36563571fdddf266ab871efcec0fbd98d3b74bff14506718aa79f9853712d640
          repository: quay.io/operator-framework/olm
        opm:
          digest: f778630c62ee19b0aeda9969c2488de88ce84d5b1d040c97a33f9f38832bab14
          repository: quay.io/operator-framework/opm
      namespace: olm
      podSecurity:
        version: v1.35
      release: v0.42.0
    role: workload
    template: local/olm
    unitType: install
  - applyWave: 0
    domain: install
    installMethod: helm
    instance: metallb
    packageInstance: metallb
    renderedPaths:
      dir: packages/metallb/install/helm
      repo: basic-infra
    renderer: helm
    repository: basic-infra
    resolvedValues:
      appVersion: v0.15.3
      chart:
        version: 0.15.3
      namespace: metallb-system
    role: workload
    template: local/metallb
    unitType: install
  - applyWave: 1
    dependsOn:
    - metallb/install
    domain: install
    installMethod: helm
    instance: nginx-ingress
    packageInstance: nginx-ingress
    renderedPaths:
      dir: packages/nginx-ingress/install/helm
      repo: basic-infra
    renderer: helm
    repository: basic-infra
    resolvedValues:
      appVersion: 1.15.1
      chart:
        version: 4.15.1
      controller:
        ingressClassResource:
          default: true
          name: nginx
        service:
          type: LoadBalancer
      namespace: ingress-nginx
    role: workload
    template: local/nginx-ingress
    unitType: install
  - applyWave: 2
    binding:
      capability: lb-ip-pool
      name: nginx-ingress-lb
      side: consumer
    dependsOn:
    - nginx-ingress/install
    - metallb/resources/pool/nginx-ingress-lb-basic-infra-dsv
    domain: resources
    instance: nginx-ingress-lb-binding-nginx-ingress-lb-basic-infra-dsv
    packageInstance: nginx-ingress
    renderedPaths:
      dir: packages/nginx-ingress/resources/lb-binding/nginx-ingress-lb-basic-infra-dsv
      repo: basic-infra-dsv
    renderer: raw
    repository: basic-infra-dsv
    resolvedValues:
      cidrs:
      - 172.18.255.200-172.18.255.210
      namespace: ingress-nginx
      poolName: ingress-pool
      serviceName: ingress-nginx-controller
    resourceName: nginx-ingress-lb-basic-infra-dsv
    resourceTemplate: lb-binding
    role: workload
    template: local/nginx-ingress
    unitType: resource
  - applyWave: 1
    binding:
      capability: lb-ip-pool
      name: nginx-ingress-lb
      side: provider
    dependsOn:
    - metallb/install
    domain: resources
    instance: metallb-pool-nginx-ingress-lb-basic-infra-dsv
    packageInstance: metallb
    renderedPaths:
      dir: packages/metallb/resources/pool/nginx-ingress-lb-basic-infra-dsv
      repo: basic-infra-dsv
    renderer: raw
    repository: basic-infra-dsv
    resolvedValues:
      cidrs:
      - 172.18.255.200-172.18.255.210
      namespace: metallb-system
      poolName: ingress-pool
    resourceName: nginx-ingress-lb-basic-infra-dsv
    resourceTemplate: pool
    role: workload
    template: local/metallb
    unitType: resource
  placeholders: null
  repositories:
  - name: basic-infra
    type: kubernetes-resources
  - name: basic-infra-dsv
    repoRef:
      name: basic-infra
    type: kubernetes-resources
  repository:
    layout: split
    outputPath: ./out/nginx-metallb-binding
  sourceProvisionRef:
    name: nginx-metallb-binding
  sources:
  - name: local
    path: ../../../gitups-packages
    type: filesystem
